### ISSUE TITLE
2024 is it still working?

### ISSUE THREAD

**Issue by Tyconfication** [danielzuegner/roomba_control#2]
Hei first of all this is one of the funniest things i see in a long time i wanna ask if its still working with the new updates of roomba? Mine is a roomba 966 is it working with that either ?

**Comment by danielzuegner** [comment]
Hi @Tyconfication, I think this should all still be working! Feel free to give it a shot and let me know if you run into problems.

**Comment by Tyconfication** [comment]
First thanks for your reply, i got one maybe "newbie" question how do i find the device interface for bluetooth with which command ?
